# main-pipeline.yml
# This is the pipeline for building and deploying the application to Development, Test and Reference

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    exclude:
      - .azuredevops
      - docs
      - scripts

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"
  imageRepository: "skigalaxy/skipassvalidator"
  runtime: "linux-x64"
  versionPrefix: "1.0.0"
  versionSuffix: "$(Rev:r)"
  ACR_SERVICE_CONNECTION: "ACR Penyland"
  AZURE_SERVICE_CONNECTION: "Azure"

# build run name
name: $(Date:yyyy).$(Date:MM).$(Date:dd).$(Rev:r)

stages:
  - stage: Build
    displayName: Build image

    jobs:
      - job: BuildImage
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET 8 SDK"
            inputs:
              packageType: sdk
              version: 8.x

          - task: DotNetCoreCLI@2
            displayName: dotnet build $(buildConfiguration)
            inputs:
              command: "build"
              projects: "src/**/*.csproj"
              arguments: "--configuration $(buildConfiguration)"

          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              command: "test"
              testRunTitle: $(Build.BuildNumber)
              projects: "Tests/**/*.csproj"
              arguments: --configuration $(buildConfiguration)

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(ACR_SERVICE_CONNECTION)

          - task: DotNetCoreCLI@2
            displayName: Build docker image
            inputs:
              command: "publish"
              publishWebProjects: false
              projects: "**/src/SkiGalaxy.SkiPassValidator.Api.csproj"
              arguments: "-c Release -r linux-x64 -p:PublishProfile=DefaultContainer -p:ContainerRegistry=penyland.azurecr.io -p:ContainerRepository=skigalaxy/skipassvalidator /p:ContainerImageTags=latest;$(Build.BuildId)"

  # - stage: Deploy
  #   displayName: Deploy image
  #   jobs:
  #     - job: DeployImage
